import Foundation
import CoreData

/// Core Data class generated by Xcode using Editor -> Create NSManagedObject Subclass
/// Requires the Core Data model to be selected in the project navigator.
@objc(MOTransformation)
public class MOTransformation: NSManagedObject {

}

extension MOTransformation {

    /// Fetch request for retrieving `MOTransformation` entities from Core Data
    @nonobjc public class func fetchRequest() -> NSFetchRequest<MOTransformation> {
        return NSFetchRequest<MOTransformation>(entityName: "CDTransformation")
    }

    @NSManaged public var id: String?       // Unique identifier for the transformation
    @NSManaged public var info: String?     // Description or additional info about the transformation
    @NSManaged public var name: String?     // Name of the transformation (e.g., Super Saiyan)
    @NSManaged public var photo: String?    // URL or path to an image representing the transformation
    @NSManaged public var hero: MOHero?     // Associated hero who undergoes this transformation

}

// MARK: - Identifiable Conformance

extension MOTransformation: Identifiable {

}
